# templates/mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.passwordSecret }}
  # name: {{ .Release.Name }}-{{ .Values.mysql.passwordSecret }}
type: Opaque
data:
  password: {{ .Values.mysql.rootPassword | b64enc | quote }}

