# templates/mysql-service.yaml
apiVersion: v1
kind: Service
metadata:
  # name: {{ .Release.Name }}-mysql
  name: {{ .Values.mysql.serviceName }}
spec:
  selector:
    app: mysql-app
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

