# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}-node-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000


