# templates/mysql-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-app
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      serviceAccountName: mysql-sa
      containers:
        - name: mysql-server
          image: {{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}
          livenessProbe:
            httpGet:
              path: /ping
              port: 3306
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: 3306
            successThreshold: 3
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.mysql.passwordSecret }}
                  key: password

