# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.nodeApp.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        sidecar.opentelemetry.io/inject: 'true'
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/stats/prometheus'
    spec:
      serviceAccountName: nodejs-sa
      containers:
        - name: frontend
          image: {{ .Values.nodeApp.image.repository }}:{{ .Values.nodeApp.image.tag }}
          ports:
            - containerPort: 3000
          env:
            - name: APP_DB_HOST
              value: {{ .Release.Name }}-{{ .Values.mysql.serviceName }}
            - name: APP_DB_USER
              value: {{ .Values.mysql.username }}

