# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nodejsapp
spec:
  replicas: {{ .Values.nodeApp.replicaCount }}
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
      annotations:
        sidecar.opentelemetry.io/inject: 'true'
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/stats/prometheus'
    spec:
      serviceAccountName: nodejs-sa
      containers:
        - name: node-app
          image: {{ .Values.nodeApp.image.repository }}:{{ .Values.nodeApp.image.tag }}
          livenessProbe:
            httpGet:
              path: /ping
              port: 3000
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: 3000
            successThreshold: 3
          ports:
            - containerPort: 3000
          env:
            - name: APP_DB_HOST
              value: {{ .Release.Name }}-{{ .Values.mysql.serviceName }}
            - name: APP_DB_USER
              value: {{ .Values.mysql.username }}

