# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nodejsapp
spec:
  replicas: {{ .Values.nodeApp.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-node-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-node-app
    spec:
      containers:
        - name: {{ .Release.Name }}-node-app
          image: {{ .Values.nodeApp.image.repository }}:{{ .Values.nodeApp.image.tag }}
          ports:
            - containerPort: 3000
          env:
            - name: APP_DB_HOST
              value: {{ .Values.mysql.serviceName }}
            - name: APP_DB_USER
              value: {{ .Values.mysql.username }}

